config/routes.rb
Swingoutlondon2::Application.routes.draw do
  devise_for :users
  resources :events, only: [:index, :show, :new, :create] do
    resources :dates, only: [:new, :create]
    resources :event_periods, only: [:new, :create, :edit, :update]
  end

  resources :event_instances, only: [:index, :destroy]

  resources :cancellations, only: [:create, :destroy]

  resources :dance_classes, only: [:index, :show, :new, :create]

  resources :venues, only: [:index]

  authenticated :user do
    root 'event_instances#index', as: :authenticated_root
  end

  root to: 'pages#home'

  # test page to show that Main.elm displays
  get '/test', to: 'pages#test'
end

app/models/event.rb
class Event < ApplicationRecord
  include Sortable

  has_many :event_seeds, inverse_of: :event, dependent: :destroy
  has_many :event_periods, through: :event_seeds
  has_many :event_instances, through: :event_seeds

  accepts_nested_attributes_for :event_seeds

  validates :name, presence: true
  # TODO: - need to separately reject totally missing generators/seeds?
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  # GET /events
  def index
    @events = Event.all.sorted
  end

  # GET /events/:id
  def show
    @event = Event.find(params[:id])
    @event_periods = @event.event_periods.order(start_date: :desc)
  end

  # GET /events/new
  def new
    @event_form = EventForm.new

    setup_venues
  end

  # POST /events
  def create
    @create_venue = event_form_params[:create_venue]

    @event_form = EventWithVenueFormBuilder.new.build(event_form_params)

    result = EventCreator.new.call(@event_form, @create_venue)
    if result.success?
      flash[:success] = result.message
      redirect_to result.event
    else
      setup_venues
      render :new
    end
  end

  class EventWithVenueFormBuilder
    def build(form_params)
      venue_params = form_params.delete(:venue)
      form_params[:venue] = Venue.new(venue_params)

      EventForm.new(form_params)
    end
  end

  private

  def event_form_params
    params.require(:event_form).permit(
      :name,
      :url,
      :frequency,
      :start_date,
      :venue_id,
      :create_venue,
      venue: %i[name address postcode url]
    )
  end
end

app/views/events/_venue_fields.html.haml
.nested-fields.panel
  %h3 New Venue
  -# %p=link_to_remove_association "Cancel", f
  =link_to "Cancel", "#"

  =render "venues/venue_fields", f: f

app/views/events/index.html.haml
%h2 Events
= render partial: "common/sieve_search_box"
%ul.no-bullet.sieve
  - @events.each do |event|
    %li
      = link_to event.name, event

app/views/events/new.html.haml
= render 'forms/errors', resource: @event_form

= form_for @event_form, url: events_path do |f|
  = f.text_field :name
  = f.url_field :url

  #venue
    = f.fields_for :venue, @event_form.venue do |fv|
      .select
        -# FIXME - form errors don't get applied to the rendered select element because of select2
        = fv.collection_select :id, @venues, :id, :name, label: "Venue", prompt: "Please select a venue"
        = link_to "New venue", "#", class: "js-new-venue"

      .nested-fields.panel{ style: "display: none" }
        %h3 New Venue
        = link_to "Cancel", "#", class: "js-cancel-new-venue"
        = render "venues/venue_fields", f: fv
        = fv.hidden_field 'create_venue', value: "foo" if @create_venue

  = f.select :frequency, [ [ "Weekly", 1 ] , [ "Intermittent", 0 ] ], include_blank: true

  = f.text_field :start_date, class: "date"

  = f.button "Create event"

app/views/events/show.html.haml
%h1= "Event: #{@event.name}"

%h2= "Periods:"
= link_to new_event_event_period_path(@event), class: "button tiny success" do
  %i.fi-plus
  New period
- if @event.last_event_period&.repeating?
  = link_to "End period", new_event_event_period_ending_path(@event, @event.last_event_period), class: "button tiny alert"

%ul.event_periods
  = render partial: :event_period, collection: @event_periods, locals: { event: @event }, layout: "common/li_layout"

%h2= "Instances:"
%ul.event_instances
  - @event.event_instances.each do |event_instance|
    %li.row
      .small-10.medium-8.columns
        = link_to l(event_instance.date), event_instance.url
        %strong Venue:
        = event_instance.venue.name
        - if event_instance.cancelled?
          %span.label.alert Cancelled
      .small-2.medium-4.columns.actions
        - if event_instance.cancelled?
          = uncancel_button_for event_instance, class: "button tiny un-cancel" do
            %span.button-text Uncancel
            %i.fi-check
        - else
          = cancel_button_for event_instance, class: "button tiny warn cancel" do
            %span.button-text Cancel
            %i.fi-x

        = button_to event_instance_path(event_instance), class: "button tiny alert delete", method: :delete, data: { confirm: "Are you sure you want to delete this instance?" } do
          %span.button-text Bin
          %i.fi-trash

= link_to new_event_date_path(@event), class: "button" do
  Add date
  %i.fi-calendar