config/routes.rb
Swingoutlondon2::Application.routes.draw do
  devise_for :users
  resources :events, only: [:index, :show, :new, :create] do
    resources :dates, only: [:new, :create]
    resources :event_periods, only: [:new, :create, :edit, :update]
  end

  resources :event_instances, only: [:index, :destroy]

  resources :cancellations, only: [:create, :destroy]

  resources :dance_classes, only: [:index, :show, :new, :create]

  resources :venues, only: [:index]

  authenticated :user do
    root 'event_instances#index', as: :authenticated_root
  end

  root to: 'pages#home'

  # test page to show that Main.elm displays
  get '/test', to: 'pages#test'
end

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Swing Out London - Lindy Hop listings"

    = stylesheet_link_tag "application"
    = stylesheet_link_tag "https://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tag

  %body
    .off-canvas-wrap{ data: { offcanvas: true } }
      .inner-wrap
        %nav.tab-bar
          %section.left-small
            %a.left-off-canvas-toggle.menu-icon{ href: "#" }
              %span

          %section.middle.tab-bar-section
            %h1.title Swing Out London

        %aside.left-off-canvas-menu
          %ul.off-canvas-list
            %li
              %label Swing Out London
            - if current_user
              %li=link_to "New Event", new_event_path
              %li=link_to "Events", events_path
              %li=link_to "Event Instances", event_instances_path
              %li=link_to "New Dance Class", new_dance_class_path
              %li=link_to "Dance Classes", dance_classes_path
              %li=link_to "Venues", venues_path
              %li
                %p="Logged in as #{current_user.email}"
              %li=link_to 'Log out', destroy_user_session_path, :method => :delete
            - else
              %li=link_to 'Log in', new_user_session_path


        %section.main-section
          - flash.each do |name, msg|
            .alert-box{ class: name, data: { alert: true } }= msg

          .row
            .columns
              = yield

        %a.exit-off-canvas

    = javascript_include_tag "application"

app/views/layouts/public.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Swing Out London - Lindy Hop listings"

    = stylesheet_link_tag "public"
    = csrf_meta_tag

  %body
    = yield

    -# = javascript_include_tag "application"